name: one_risk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.1.1 
  async: ^2.12.0
  boolean_selector: ^2.1.2
  characters: ^1.3.0
  clock: ^1.1.2
  collection: ^1.19.0
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  matcher: ^0.12.17
  material_color_utilities: ^0.11.0
  meta: ^1.15.0
  path: ^1.9.1
  source_span: ^1.10.1
  stack_trace: ^1.12.0
  stream_channel: ^2.1.2
  string_scanner: ^1.3.0
  term_glyph: ^1.2.1
  test_api: ^0.7.3
  vm_service: ^14.3.0





dev_dependencies:

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
